[package]
name = "hacker-pie"
version = "0.1.0"
authors = ["kingdido999 <info@desmonding.me>"]
edition = "2018"

[dependencies]
pulldown-cmark = "0.2.0"
tera = "0.11"
serde = "1.0"
serde_derive = "1.0"
